export const IQ_MASTER_BONUS = 0.05
export const PERFECT_NINJUTSU_DEFENSE_REDUCTION = 0.20
export const PERFECT_TAIJUTSU_NINJUTSU_BONUS = 0.50
export const EIGHT_GATES_BONUS = 0.50
export const BIJU_GENJUTSU_PENALTY_POINTS = 15
export const UZUMAKI_CHAKRA_BONUS = 0.25
export const SENJU_CHAKRA_BONUS = 0.10
export const OTSUTSUKI_BONUS = 0.35